SuperheroSocialClub/Models/SuperheroModel.cs
namespace SuperheroSocialClub.Models
{
    public class SuperheroModel
    {
        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public string? SecretIdentity { get; set; }
        public List<string> Superpower { get; set; } = new();
        public string? Image { get; set; }

        public SuperheroModel()
        {
            //Image = RandomImage();
        }

        private string RandomImage()
        {
            return $"superhero{new Random().Next(1, 21)}.jpg";
        }
    }


}

SuperheroSocialClub/Pages/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SuperheroSocialClub.Database;
using SuperheroSocialClub.Models;

namespace SuperheroSocialClub.Pages
{
    [BindProperties]
    public class AddModel : PageModel
    {

        public string Name { get; set; }
        public string SecretIdentity { get; set; }
        public string Superpower { get; set; }
        public List<string> SuperpowersList { get; set; } = SuperheroRepo.Superpowers;
        public string Image { get; set; }
        private static string image = "";


        public void OnGet()
        {
            SuperheroRepo.Superpowers.Clear();
            image = SuperheroRepo.RandomImage();
            Image = image;
        }

        public IActionResult OnPostAddSuperhero()
        {
            //if (!ModelState.IsValid)
            //{
            //    return Page();
            //}

            List<string> superPowers = new(SuperheroRepo.Superpowers);

            SuperheroRepo.Superheroes.Add(new SuperheroModel
            {
                Id = SuperheroRepo.Superheroes.Count + 1,
                Name = Name,
                SecretIdentity = SecretIdentity,
                Superpower = superPowers,
                Image = image
            });

            return RedirectToPage("/Index");
        }

        public void OnPostAddSuperpower()
        {
            SuperheroRepo.Superpowers.Add(Superpower);
            SuperpowersList = SuperheroRepo.Superpowers;
            Image = image;
        }
    }
}

SuperheroSocialClub/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SuperheroSocialClub.Database;
using SuperheroSocialClub.Models;

namespace SuperheroSocialClub.Pages
{
    [BindProperties]
    public class EditModel : PageModel
    {
        public SuperheroModel? Superhero { get; set; }
        public string? Image { get; set; }
        public string? Name { get; set; }
        public string? SecretIdentity { get; set; }
        public string? Superpower { get; set; }
        public void OnGet(int id)
        {
            Superhero = SuperheroRepo.Superheroes.FirstOrDefault(hero => hero.Id == id);

            Image = Superhero.Image;
            Name = Superhero.Name;
            SecretIdentity = Superhero.SecretIdentity;
            //Superpower = Superhero.Superpower;
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var superheroToUpdate = SuperheroRepo.Superheroes.FirstOrDefault(hero => hero.Id == Superhero.Id);


            superheroToUpdate.Name = Name;
            superheroToUpdate.SecretIdentity = SecretIdentity;
            //superheroToUpdate.Superpower = Superpower;


            return RedirectToPage("/Index");
        }
    }
}

SuperheroSocialClub/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SuperheroSocialClub.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}

}

SuperheroSocialClub/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SuperheroSocialClub.Database;
using SuperheroSocialClub.Models;

namespace SuperheroSocialClub.Pages
{
    public class IndexModel : PageModel
    {
        public List<SuperheroModel>? Superheroes { get; set; }
        public void OnGet()
        {
            Superheroes = SuperheroRepo.Superheroes;
        }

        public IActionResult OnPostDeleteHero(int id)
        {
            SuperheroModel? superheroToDelete = SuperheroRepo.Superheroes.FirstOrDefault(s => s.Id == id);

            if (superheroToDelete != null)
            {
                SuperheroRepo.Superheroes.Remove(superheroToDelete);
            }

            Superheroes = SuperheroRepo.Superheroes;
            return Page();
        }
    }
}

SuperheroSocialClub/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SuperheroSocialClub.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}

}

SuperheroSocialClub/Pages/Add.cshtml
@page
@model SuperheroSocialClub.Pages.AddModel
@{
}

@* Bara en placeholder *@
<h1>Here you can add your superhero</h1>

<form method="post" class="mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img class="card-img" src="~/images/@Model.Image" alt="Card image cap">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <div class="form-group mb-1">
                                <input type="text" class="form-control" placeholder="Name" asp-for="@Model.Name" />
                            </div>
                            <div class="form-group mb-1">
                                <input type="text" class="form-control" placeholder="Secret Identity" asp-for="@Model.SecretIdentity" />
                            </div>
                            <div class="form-group mb-1">
                                <input type="text" class="form-control" placeholder="Superpower" asp-for="@Model.Superpower" />
                            </div>
                            <ul>
                                @foreach (string superpower in Model.SuperpowersList)
                                {
                                    <li>@superpower</li>
                                }
                            </ul>

                            <input class="btn btn-danger" type="submit" value="Add superpower" asp-page-handler="AddSuperpower" />

                            <input class="btn btn-primary" type="submit" value="Add superhero" asp-page-handler="AddSuperhero" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

SuperheroSocialClub/Pages/Edit.cshtml
@page
@model SuperheroSocialClub.Pages.EditModel
@{
}

@* Bara en placeholder *@

<div class="container">
    <h1 class="text-center">Here you can edit your superhero</h1>

    <form method="post" class="mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">               
                <div class="card shadow">                    
                    <div class="row no-gutters">                        
                        <div class="col-md-4">                           
                            <img class="card-img" src="~/images/@Model.Image" alt="Card image cap">
                        </div>
                        <div class="col-md-8">                         
                            <div class="card-body">
                                <div class="form-group mb-1">
                                    <input type="text" class="form-control" placeholder="Name" asp-for="@Model.Name" />
                                </div>
                                <div class="form-group mb-1">
                                    <input type="text" class="form-control" placeholder="Secret Identity" asp-for="@Model.SecretIdentity" />
                                </div>
                                <div class="form-group mb-1">
                                    <input type="text" class="form-control" placeholder="Can't edit superpowers'" asp-for="@Model.Superpower" />
                                </div>
                                <br />
                                <button class="btn btn-warning btn-block" type="submit">Update superhero</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

SuperheroSocialClub/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container row">
    <div class="navbar justify-content-around border-bottom">
        <a class="btn btn-success" asp-page="Add">Add superhero</a>
    </div>

    @if(Model.Superheroes != null)
    {
        @foreach(var superhero in Model.Superheroes)
        {
            <div class="col-3 justify-content-center mt-4">
                <div class="card shadow" style="width: 100%;">
                    <img class="card-img-top" src="~/images/@superhero.Image" alt="Card image cap">
                    <div class="card-body">
                        <h1>@superhero.Name</h1>
                        <h3 class="fw-normal fst-italic"><span class="fw-bold">Secret identity </span>@superhero.SecretIdentity</h3>
                        <div class="row">
                            <h3><span class="fw-bold">Superpowers: </span></h3>
                             @foreach (string superpower in superhero.Superpower)
                            {
                                <div class="col-6">
                                    <h4 class="fw-normal fst-italic">@superpower</h4>
                                </div>
                            }
                        </div>
                        <form method="post"> 
                            <a class="btn btn-danger" asp-page="Edit" asp-route-id="@superhero.Id">Edit</a>
                            <input type="submit" value="Delete" class="btn btn-dark" asp-page-handler="DeleteHero" asp-route-id="@superhero.Id"/>
                        </form>
                    </div>
                </div>
            </div>
        }
    }

</div>

SuperheroSocialClub/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperheroSocialClub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SuperheroSocialClub.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SuperheroSocialClub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SuperheroSocialClub - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>